#!/usr/bin/env node
// ============================================================
// D.A.T.I. — Migration 005 — backfill_join_codes (DOWN)
//
// WARNING: This rollback is COARSE. The up-script did not persist
// a log of which event IDs it touched, so this script nulls the
// join_code for ALL events currently in status 'published' or 'live'
// — including any codes that were generated by runtime publish
// transitions after the backfill ran. If you need to preserve
// specific codes, `mysqldump` the events table first.
//
// Practical effect after running:
//   * Every published / live event ends up with join_code = NULL.
//   * Hosts will need to unpublish + republish each event to get
//     fresh codes (or re-run the up-script).
//
// Run:
//   node db/migrations/005_backfill_join_codes.down.js
// ============================================================

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env') });
const mysql = require('mysql2/promise');

async function main() {
    const pool = await mysql.createPool({
        host:     process.env.DB_HOST || 'localhost',
        user:     process.env.DB_USER || 'dati',
        password: process.env.DB_PASSWORD || '',
        database: process.env.DB_NAME || 'dati_trivia',
        port:     process.env.DB_PORT || 3306,
        connectionLimit: 2,
    });
    try {
        const [result] = await pool.query(
            `UPDATE events SET join_code = NULL
              WHERE status IN ('published', 'live') AND join_code IS NOT NULL`
        );
        console.log(`Cleared join_code on ${result.affectedRows} event(s).`);
    } finally {
        await pool.end();
    }
}

main()
    .then(() => process.exit(0))
    .catch(err => { console.error('FATAL:', err); process.exit(2); });
